package bundle

import (
	"fmt"
	"strings"
	"time"
)

// GenerateReplayScript builds the `replay.sh` text embedded in every
// bundle. It's deliberately minimal — one real command so there's
// nothing to break — and uses a literal path to the bundle. Users who
// rename a bundle should re-invoke `faultbox replay <new-name>`
// directly rather than editing the script.
//
// bundleBasename is the *filename* of the bundle (not a full path):
// replay.sh lives inside the archive and resolves its sibling via
// $(dirname "$0"). faultboxVersion is stamped into a header comment
// so a reader knows which tool produced this script.
func GenerateReplayScript(bundleBasename, faultboxVersion string, createdAt time.Time) []byte {
	// Belt-and-braces: reject any shell-metacharacter in the bundle
	// name so the script can't be coerced into running arbitrary code
	// if a user has somehow crafted a malicious filename. In practice
	// DefaultFilename() produces names that are always safe.
	safe := sanitiseBasename(bundleBasename)

	var b strings.Builder
	fmt.Fprintf(&b, "#!/usr/bin/env sh\n")
	fmt.Fprintf(&b, "# Generated by faultbox %s at %s\n", faultboxVersion, createdAt.UTC().Format(time.RFC3339))
	fmt.Fprintf(&b, "# Reproduces this run. Pass --test <name> to re-run a single test.\n")
	fmt.Fprintf(&b, "set -eu\n")
	fmt.Fprintf(&b, "DIR=\"$(CDPATH= cd -- \"$(dirname -- \"$0\")\" && pwd)\"\n")
	fmt.Fprintf(&b, "exec faultbox replay \"$DIR/%s\" \"$@\"\n", safe)
	return []byte(b.String())
}

// sanitiseBasename strips control characters and anything that would
// matter to a POSIX shell from a filename before interpolation. The
// allowlist mirrors the characters emitted by DefaultFilename() plus
// a handful of common safe extras.
func sanitiseBasename(name string) string {
	var b strings.Builder
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z',
			r >= 'A' && r <= 'Z',
			r >= '0' && r <= '9',
			r == '-', r == '_', r == '.', r == 'T':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	s := b.String()
	if s == "" {
		return "bundle.fb"
	}
	return s
}
