// Package report builds a single self-contained `report.html` from one
// `.fb` bundle (RFC-025). It is the implementation behind `faultbox
// report <bundle.fb>` shipped in v0.11.0 per RFC-029.
//
// The output is one HTML file. No network fetches, no external assets.
// Users can email it, attach it in Slack, commit it to git, or publish
// it as a CI artifact — and it keeps working, offline, forever. The
// same "one file, inlined data" trick R-Studio notebooks pioneered for
// data science.
//
// Data flow:
//
//	bundle (tar.gz) ──► Reader ──► Data (manifest + env + trace) ──►
//	  html/template ──► report.html (CSS+JS embedded via go:embed)
//
// The Go side is a dumb renderer: it gathers the three JSONs from the
// bundle, builds a single JS object literal on window.__FAULTBOX__, and
// writes the HTML shell. All visualisation logic lives in app.js; all
// styling lives in style.css. Both are //go:embed'd at compile time so
// the binary remains a single artifact.
package report

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"fmt"
	"html/template"
	"io"
	"os"
	"strings"
	"time"

	"github.com/faultbox/Faultbox/internal/bundle"
)

//go:embed template.html
var templateHTML string

//go:embed app.js
var appJS string

//go:embed style.css
var styleCSS string

// Data is the bundle contents shaped for the HTML template. Only the
// fields listed here are serialised into the inlined
// `window.__FAULTBOX__` object; everything the JS side needs must go
// through here.
//
// `Specs` carries every `spec/*.star` file captured in the bundle
// (RFC-025 Phase 4). The JS renders a top-level collapsible "Spec"
// section and cross-links from the coverage table + drill-down to
// specific lines in these files. Keys are paths relative to the
// archive root, e.g. "spec/faultbox.star".
type Data struct {
	Manifest *bundle.Manifest  `json:"manifest"`
	Env      *bundle.Env       `json:"env,omitempty"`
	Trace    json.RawMessage   `json:"trace,omitempty"`
	Specs    map[string]string `json:"specs,omitempty"`
}

// templateContext carries the values the html/template substitutes.
// Fields are either safe HTML (CSS/JS we control) or a JSON literal
// we've already escaped for <script> context.
type templateContext struct {
	Title           string
	Subtitle        string
	GeneratedAt     string
	FaultboxVersion string
	StyleCSS        template.CSS
	AppJS           template.JS
	DataJSON        template.JS
}

// Build reads a bundle and writes a single self-contained report.html
// to the writer. All styles and scripts are inlined; the resulting
// file has zero external dependencies and can be emailed, slacked, or
// checked into git without breaking.
//
// faultboxVersion is the version of the caller — used for the
// generator footer and for a best-effort "generated by" line; it does
// not gate rendering on version compatibility (RFC-025 inspect policy
// applies here too: never refuse on a read-only path).
func Build(w io.Writer, r *bundle.Reader, faultboxVersion string) error {
	data, err := gatherData(r)
	if err != nil {
		return fmt.Errorf("gather bundle data: %w", err)
	}

	payload, err := json.Marshal(data)
	if err != nil {
		return fmt.Errorf("marshal report payload: %w", err)
	}

	ctx := templateContext{
		Title:           reportTitle(data.Manifest),
		Subtitle:        reportSubtitle(data.Manifest),
		GeneratedAt:     time.Now().UTC().Format(time.RFC3339),
		FaultboxVersion: faultboxVersion,
		StyleCSS:        template.CSS(styleCSS),
		// Both the app JS and the JSON payload sit inside <script>
		// tags; any literal "</script" in their contents would close
		// the tag early and fold the remainder into HTML. We neutralise
		// the sequence with a backslash escape that JavaScript's string
		// and comment lexers both accept.
		AppJS:    template.JS(escapeScriptContent(appJS)),
		DataJSON: template.JS(inlineJSON(payload)),
	}

	t, err := template.New("report").Parse(templateHTML)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, ctx); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}
	if _, err := w.Write(buf.Bytes()); err != nil {
		return fmt.Errorf("write report: %w", err)
	}
	return nil
}

// BuildToFile is Build's path-based sibling. It writes atomically
// (tmp + rename) so a half-written report never appears on disk —
// important in CI where the report might be picked up by a watcher
// the moment it lands.
func BuildToFile(path string, r *bundle.Reader, faultboxVersion string) error {
	tmp, err := os.CreateTemp(dirOf(path), ".report-*.tmp")
	if err != nil {
		return fmt.Errorf("create tmp: %w", err)
	}
	tmpName := tmp.Name()
	defer func() { _ = os.Remove(tmpName) }()

	if err := Build(tmp, r, faultboxVersion); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close tmp: %w", err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("rename into place: %w", err)
	}
	return nil
}

func dirOf(path string) string {
	if i := strings.LastIndexByte(path, '/'); i >= 0 {
		return path[:i]
	}
	return "."
}

func gatherData(r *bundle.Reader) (*Data, error) {
	m := r.Manifest()
	if m == nil {
		return nil, fmt.Errorf("bundle has no manifest.json")
	}

	d := &Data{Manifest: m, Env: r.Env()}

	// trace.json may be absent on older bundles or for pass-only
	// runs where no trace was emitted; the report still renders
	// without it (just no drill-down or matrix detail).
	if raw, err := r.File("trace.json"); err == nil && len(raw) > 0 {
		d.Trace = json.RawMessage(raw)
	}

	// Collect every spec/*.star file so the JS side can render the
	// top-level Spec section and cross-link from coverage/topology
	// to specific service/test definitions.
	specs := map[string]string{}
	for _, name := range r.Files() {
		if !strings.HasPrefix(name, "spec/") || !strings.HasSuffix(name, ".star") {
			continue
		}
		raw, err := r.File(name)
		if err != nil || len(raw) == 0 {
			continue
		}
		specs[name] = string(raw)
	}
	if len(specs) > 0 {
		d.Specs = specs
	}
	return d, nil
}

// inlineJSON escapes a JSON byte slice so it is safe to embed as a
// JavaScript expression inside a <script> tag. The html/template
// package will happily emit `</script>` verbatim if we pass a
// template.JS value; we defuse it manually. U+2028/U+2029 are also
// handled because, while valid in JSON, they terminate lines in
// ECMAScript <5 (and some older JSON parsers still care).
func inlineJSON(b []byte) string {
	s := string(b)
	s = strings.ReplaceAll(s, "</", "<\\/")
	s = strings.ReplaceAll(s, "\u2028", "\\u2028")
	s = strings.ReplaceAll(s, "\u2029", "\\u2029")
	return s
}

// escapeScriptContent neutralises the one sequence that would close a
// surrounding <script> tag if it appeared in the embedded JS source —
// "</" anywhere inside (most commonly "</script>" in a comment). A
// backslash escape is harmless in both string literals and block
// comments, so we apply it unconditionally rather than trying to be
// clever about where in the source the sequence appears.
func escapeScriptContent(s string) string {
	return strings.ReplaceAll(s, "</", "<\\/")
}

func reportTitle(m *bundle.Manifest) string {
	if m == nil || m.RunID == "" {
		return "Faultbox Report"
	}
	return fmt.Sprintf("Faultbox Report — %s", m.RunID)
}

func reportSubtitle(m *bundle.Manifest) string {
	if m == nil {
		return ""
	}
	s := m.Summary
	switch {
	case s.Total == 0:
		return "No tests ran."
	case s.Failed == 0 && s.Errored == 0:
		return fmt.Sprintf("All %d check%s held up under the injected faults.",
			s.Total, plural(s.Total))
	case s.Errored > 0:
		return fmt.Sprintf("%d of %d checks held; %d regressed, %d errored.",
			s.Passed, s.Total, s.Failed, s.Errored)
	default:
		return fmt.Sprintf("%d of %d checks held; %d regressed under fault.",
			s.Passed, s.Total, s.Failed)
	}
}

func plural(n int) string {
	if n == 1 {
		return ""
	}
	return "s"
}
