// Package report builds a single self-contained `report.html` from one
// `.fb` bundle (RFC-025). It is the implementation behind `faultbox
// report <bundle.fb>` shipped in v0.11.0 per RFC-029.
//
// The output is one HTML file. No network fetches, no external assets.
// Users can email it, attach it in Slack, commit it to git, or publish
// it as a CI artifact — and it keeps working, offline, forever. The
// same "one file, inlined data" trick R-Studio notebooks pioneered for
// data science.
//
// Data flow:
//
//	bundle (tar.gz) ──► Reader ──► Data (manifest + env + trace) ──►
//	  html/template ──► report.html (CSS+JS embedded via go:embed)
//
// The Go side is a dumb renderer: it gathers the three JSONs from the
// bundle, builds a single JS object literal on window.__FAULTBOX__, and
// writes the HTML shell. All visualisation logic lives in app.js; all
// styling lives in style.css. Both are //go:embed'd at compile time so
// the binary remains a single artifact.
package report

import (
	"bytes"
	"compress/gzip"
	_ "embed"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"html/template"
	"io"
	"os"
	"strings"
	"time"

	"github.com/faultbox/Faultbox/internal/bundle"
)

//go:embed template.html
var templateHTML string

//go:embed app.js
var appJS string

//go:embed style.css
var styleCSS string

// Data is the bundle contents shaped for the HTML template. Only the
// fields listed here are serialised into the inlined
// `window.__FAULTBOX__` object; everything the JS side needs must go
// through here.
//
// `Specs` carries every `spec/*.star` file captured in the bundle
// (RFC-025 Phase 4). The JS renders a top-level collapsible "Spec"
// section and cross-links from the coverage table + drill-down to
// specific lines in these files. Keys are paths relative to the
// archive root, e.g. "spec/faultbox.star".
type Data struct {
	Manifest *bundle.Manifest  `json:"manifest"`
	Env      *bundle.Env       `json:"env,omitempty"`
	Trace    json.RawMessage   `json:"trace,omitempty"`
	Specs    map[string]string `json:"specs,omitempty"`
}

// templateContext carries the values the html/template substitutes.
// Fields are either safe HTML (CSS/JS we control) or an
// already-safe-for-<script> base64 string.
//
// Data is inlined as gzip+base64 per RFC-031 (#83). Typical shrink
// on a PoC-scale bundle: ~22 MB raw events JSON → ~4-5 MB base64.
// The JS side decompresses on open via the DecompressionStream API
// (Chrome 80+, Safari 16.4+, Firefox 113+). Base64 is chosen over
// hex because it yields ~33% rather than 100% overhead and contains
// no characters that the HTML parser treats specially inside a
// <script type="application/octet-stream"> block.
type templateContext struct {
	Title           string
	Subtitle        string
	GeneratedAt     string
	FaultboxVersion string
	StyleCSS        template.CSS
	AppJS           template.JS
	DataB64         template.JS
	SizeBanner      string
	Mode            string
}

// Options tunes report rendering. Added in v0.12 (RFC-031 #83) to
// give `faultbox report` a smaller default output and an opt-in
// summary mode for CI artifact uploads.
//
//   - Summary=true drops the bundle's trace entirely, leaving only
//     the manifest and env data the matrix/tests/coverage sections
//     need. Typical output: <100 KB. The drill-down modal becomes a
//     "re-run to see details" hint.
type Options struct {
	Summary bool
}

// Build reads a bundle and writes a single self-contained report.html
// to the writer. All styles, scripts, and bundle data are inlined; the
// resulting file has zero external dependencies and can be emailed,
// Slack'd, or checked into git without breaking.
//
// Data is inlined as gzip+base64 (RFC-031) and decompressed by the
// page on open via the DecompressionStream browser API.
//
// faultboxVersion is the version of the caller — used for the
// generator footer and for a best-effort "generated by" line; it does
// not gate rendering on version compatibility (RFC-025 inspect policy
// applies here too: never refuse on a read-only path).
func Build(w io.Writer, r *bundle.Reader, faultboxVersion string) error {
	return BuildWithOptions(w, r, faultboxVersion, Options{})
}

// BuildWithOptions is Build with explicit rendering options.
func BuildWithOptions(w io.Writer, r *bundle.Reader, faultboxVersion string, opts Options) error {
	data, err := gatherData(r)
	if err != nil {
		return fmt.Errorf("gather bundle data: %w", err)
	}

	if opts.Summary {
		// Drop the trace — by far the biggest contributor to
		// report size on PoC-sized bundles. Downstream sections that
		// need it (matrix drill-down, swim-lane viewer) detect the
		// absence and render a "re-run with full trace" hint.
		data.Trace = nil
	}

	payload, err := json.Marshal(data)
	if err != nil {
		return fmt.Errorf("marshal report payload: %w", err)
	}

	gz, err := gzipBytes(payload)
	if err != nil {
		return fmt.Errorf("gzip payload: %w", err)
	}
	// URL-safe base64 alphabet (- and _ instead of + and /). Avoids
	// html/template HTML-escaping `+` to `&#43;` inside <script> tags
	// with unrecognised type= attributes. The JS side reverses the
	// substitution before calling atob().
	b64 := base64.URLEncoding.EncodeToString(gz)

	ctx := templateContext{
		Title:           reportTitle(data.Manifest),
		Subtitle:        reportSubtitle(data.Manifest),
		GeneratedAt:     time.Now().UTC().Format(time.RFC3339),
		FaultboxVersion: faultboxVersion,
		StyleCSS:        template.CSS(styleCSS),
		// The app JS still sits inside a <script> tag; a literal
		// "</script" in its body would close the tag early and fold
		// the remainder into HTML. The data block is now base64
		// (no "<" or "/" in the alphabet) so it needs no escape.
		AppJS:      template.JS(escapeScriptContent(appJS)),
		DataB64:    template.JS(b64),
		SizeBanner: sizeBanner(len(payload), len(b64), opts.Summary),
		Mode:       modeLabel(opts.Summary),
	}

	t, err := template.New("report").Parse(templateHTML)
	if err != nil {
		return fmt.Errorf("parse template: %w", err)
	}
	var buf bytes.Buffer
	if err := t.Execute(&buf, ctx); err != nil {
		return fmt.Errorf("execute template: %w", err)
	}
	if _, err := w.Write(buf.Bytes()); err != nil {
		return fmt.Errorf("write report: %w", err)
	}
	return nil
}

// BuildToFile is Build's path-based sibling. It writes atomically
// (tmp + rename) so a half-written report never appears on disk —
// important in CI where the report might be picked up by a watcher
// the moment it lands.
func BuildToFile(path string, r *bundle.Reader, faultboxVersion string) error {
	return BuildToFileWithOptions(path, r, faultboxVersion, Options{})
}

// BuildToFileWithOptions is BuildToFile with explicit options.
func BuildToFileWithOptions(path string, r *bundle.Reader, faultboxVersion string, opts Options) error {
	tmp, err := os.CreateTemp(dirOf(path), ".report-*.tmp")
	if err != nil {
		return fmt.Errorf("create tmp: %w", err)
	}
	tmpName := tmp.Name()
	defer func() { _ = os.Remove(tmpName) }()

	if err := BuildWithOptions(tmp, r, faultboxVersion, opts); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return fmt.Errorf("close tmp: %w", err)
	}
	if err := os.Rename(tmpName, path); err != nil {
		return fmt.Errorf("rename into place: %w", err)
	}
	return nil
}

// gzipBytes compresses b with gzip at default compression. Default
// level is the right choice for report data — the payload is
// structured JSON with high redundancy, so the incremental shrink
// from BestCompression over DefaultCompression is small while the
// CPU cost is ~3x.
func gzipBytes(b []byte) ([]byte, error) {
	var buf bytes.Buffer
	gz := gzip.NewWriter(&buf)
	if _, err := gz.Write(b); err != nil {
		return nil, err
	}
	if err := gz.Close(); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// sizeBanner renders the header indicator that tells the reader
// whether this report is full or summary and how big the payload is.
// Users cared about size after hitting upload limits with 23 MB
// reports (customer feedback, v0.11.1 regression report).
func sizeBanner(rawBytes, encodedBytes int, summary bool) string {
	kind := "full"
	if summary {
		kind = "summary"
	}
	return fmt.Sprintf("%s · %s → %s (gzip+base64)",
		kind, humanBytes(rawBytes), humanBytes(encodedBytes))
}

func modeLabel(summary bool) string {
	if summary {
		return "summary"
	}
	return "full"
}

// humanBytes formats a byte count in IEC-ish units. Reports never
// exceed GB in practice so we stop at MB for readability; a TB-sized
// report would be a bug long before it was a display issue.
func humanBytes(n int) string {
	switch {
	case n < 1024:
		return fmt.Sprintf("%d B", n)
	case n < 1024*1024:
		return fmt.Sprintf("%.1f KB", float64(n)/1024)
	default:
		return fmt.Sprintf("%.1f MB", float64(n)/(1024*1024))
	}
}

func dirOf(path string) string {
	if i := strings.LastIndexByte(path, '/'); i >= 0 {
		return path[:i]
	}
	return "."
}

func gatherData(r *bundle.Reader) (*Data, error) {
	m := r.Manifest()
	if m == nil {
		return nil, fmt.Errorf("bundle has no manifest.json")
	}

	d := &Data{Manifest: m, Env: r.Env()}

	// trace.json may be absent on older bundles or for pass-only
	// runs where no trace was emitted; the report still renders
	// without it (just no drill-down or matrix detail).
	if raw, err := r.File("trace.json"); err == nil && len(raw) > 0 {
		d.Trace = json.RawMessage(raw)
	}

	// Collect every spec/*.star file so the JS side can render the
	// top-level Spec section and cross-link from coverage/topology
	// to specific service/test definitions.
	specs := map[string]string{}
	for _, name := range r.Files() {
		if !strings.HasPrefix(name, "spec/") || !strings.HasSuffix(name, ".star") {
			continue
		}
		raw, err := r.File(name)
		if err != nil || len(raw) == 0 {
			continue
		}
		specs[name] = string(raw)
	}
	if len(specs) > 0 {
		d.Specs = specs
	}
	return d, nil
}

// escapeScriptContent neutralises the one sequence that would close a
// surrounding <script> tag if it appeared in the embedded JS source —
// "</" anywhere inside (most commonly "</script>" in a comment). A
// backslash escape is harmless in both string literals and block
// comments, so we apply it unconditionally rather than trying to be
// clever about where in the source the sequence appears.
func escapeScriptContent(s string) string {
	return strings.ReplaceAll(s, "</", "<\\/")
}

func reportTitle(m *bundle.Manifest) string {
	if m == nil || m.RunID == "" {
		return "Faultbox Report"
	}
	return fmt.Sprintf("Faultbox Report — %s", m.RunID)
}

func reportSubtitle(m *bundle.Manifest) string {
	if m == nil {
		return ""
	}
	s := m.Summary
	switch {
	case s.Total == 0:
		return "No tests ran."
	case s.Failed == 0 && s.Errored == 0:
		return fmt.Sprintf("All %d check%s held up under the injected faults.",
			s.Total, plural(s.Total))
	case s.Errored > 0:
		return fmt.Sprintf("%d of %d checks held; %d regressed, %d errored.",
			s.Passed, s.Total, s.Failed, s.Errored)
	default:
		return fmt.Sprintf("%d of %d checks held; %d regressed under fault.",
			s.Passed, s.Total, s.Failed)
	}
}

func plural(n int) string {
	if n == 1 {
		return ""
	}
	return "s"
}
