// Package seccheck implements gVisor's remote trace-point sink protocol.
//
// Under runsc, the Sentry can stream structured trace points to a monitoring
// process over a SOCK_SEQPACKET Unix socket. Faultbox uses that to observe
// filesystem I/O with detail seccomp-notify cannot reach: the Sentry reports
// the *resolved* path, the byte offset, the requested count, and the real
// errno, all without racing the SUT or truncating at 256 bytes.
//
// RFC-054 calls this "Path C-lite": most of L2's observation value without
// forking the Sentry.
//
// Three limits, all established by the M0.3 spike and all load-bearing:
//
//   - The protocol is OBSERVE-ONLY. The Sentry's own README states the monitor
//     writes exactly once, during the handshake, and only reads afterwards.
//     There is no return path, so nothing here can deny or delay a syscall.
//   - There is NO fsync trace point. gVisor traces 42 syscalls and
//     fsync/fdatasync/msync/sync_file_range are not among them.
//   - openat reports the raw syscall argument, which is frequently relative.
//     read/write/close carry the Sentry-resolved absolute fd_path, so path
//     matching keys on those.
//
// The Sentry is untrusted in gVisor's own threat model, so every field this
// package decodes is bounded before use.
package seccheck

import (
	"encoding/binary"
	"errors"
	"fmt"
	"net"
	"os"
	"path"
	"sync"
	"sync/atomic"

	"google.golang.org/protobuf/proto"
	pb "gvisor.dev/gvisor/pkg/sentry/seccheck/points/points_go_proto"
)

// Wire-protocol constants, deliberately duplicated rather than imported from
// gvisor.dev/gvisor/pkg/sentry/seccheck/sinks/remote/wire.
//
// That package carries an autogenerated ABI file importing pkg/hostarch, whose
// init() panics with "Only 4K page size is supported on arm64" — macOS uses
// 16K pages. Importing it would make this package, and every test that touches
// it, unloadable on an Apple Silicon dev machine. Since the whole point of the
// fixture strategy is that the decoder is testable with no runsc and no Linux,
// two small constants are the cheaper trade.
//
// wire_check_linux.go asserts at compile time that these still agree with
// gVisor, so a future protocol change cannot drift silently.
const (
	// headerStructSize mirrors wire.HeaderStructSize.
	headerStructSize = 8
	// protocolVersion mirrors wire.CurrentVersion.
	protocolVersion = 1
)

// Op is the filesystem operation a FileIO describes.
type Op string

const (
	OpOpen    Op = "open"
	OpRead    Op = "read"
	OpWrite   Op = "write"
	OpClose   Op = "close"
	OpConnect Op = "connect"
)

// aarch64/amd64 syscall numbers needed to tell a positional I/O call from a
// sequential one. pwrite64 and write share MESSAGE_SYSCALL_WRITE and are
// distinguished only by sysno — a decoder switching on message type alone
// silently conflates them (M0.3 finding).
const (
	sysPwrite64ARM64 = 68 // write is 64
	sysPwrite64AMD64 = 18 // write is 1
	sysPread64ARM64  = 67 // read is 63
	sysPread64AMD64  = 17 // read is 0
)

// FileIO is one normalized filesystem operation.
type FileIO struct {
	Op   Op
	Path string
	FD   int64
	// Count is the bytes requested; Result the bytes actually transferred (or
	// the new fd for open). A Result short of Count is a short read/write.
	Count  uint64
	Result int64
	// Offset is meaningful only when HasOffset — that is, for the positional
	// variants (pread64/pwrite64). Sequential read/write carry no offset.
	Offset    int64
	HasOffset bool
	// Errno is the real error from the Sentry, not an inference. Zero on
	// success.
	Errno       int64
	PID         int32
	TID         int32
	ProcessName string
	ContainerID string
	// Positional reports whether the call was a p-variant.
	Positional bool
	// TimeNs is the Sentry's timestamp.
	TimeNs int64
}

// ShortTransfer reports whether fewer bytes moved than were requested. Only
// meaningful for reads and writes that succeeded.
func (f FileIO) ShortTransfer() bool {
	if f.Op != OpRead && f.Op != OpWrite {
		return false
	}
	return f.Errno == 0 && f.Result >= 0 && uint64(f.Result) < f.Count
}

// OnFileIO receives each decoded operation. Called from the sink's read
// goroutine, so it must not block.
type OnFileIO func(FileIO)

// Sink is a listening remote-sink server.
type Sink struct {
	path    string
	ln      *net.UnixListener
	onIO    OnFileIO
	onError func(error)

	wg     sync.WaitGroup
	closed atomic.Bool

	points  atomic.Int64
	dropped atomic.Int64
}

// Config configures a Sink.
type Config struct {
	// Path is the UDS to create. The Sentry connects to it.
	Path string
	// OnFileIO receives decoded operations.
	OnFileIO OnFileIO
	// OnError receives decode failures. Optional; failures are otherwise
	// counted but not surfaced.
	OnError func(error)
}

// maxMessage bounds a single datagram. The Sentry is untrusted, so this is a
// hard cap rather than a hint: SOCK_SEQPACKET truncates anything larger, which
// fails the decode instead of allocating without limit.
const maxMessage = 1 << 20

// maxPathLen bounds a decoded path before it reaches the event log.
const maxPathLen = 4096

// Listen creates the socket and starts accepting. The socket must exist
// before the sandbox starts, or the Sentry's connect fails and — with
// ignore_setup_error=false — the sandbox refuses to boot.
func Listen(cfg Config) (*Sink, error) {
	if cfg.Path == "" {
		return nil, errors.New("seccheck: socket path is required")
	}
	_ = os.Remove(cfg.Path)

	ln, err := net.ListenUnix("unixpacket", &net.UnixAddr{Name: cfg.Path, Net: "unixpacket"})
	if err != nil {
		return nil, fmt.Errorf("seccheck: listen on %s: %w", cfg.Path, err)
	}
	// The socket carries the SUT's filesystem activity; keep it owner-only.
	if err := os.Chmod(cfg.Path, 0o600); err != nil {
		ln.Close()
		return nil, fmt.Errorf("seccheck: chmod %s: %w", cfg.Path, err)
	}

	s := &Sink{path: cfg.Path, ln: ln, onIO: cfg.OnFileIO, onError: cfg.OnError}
	s.wg.Add(1)
	go s.acceptLoop()
	return s, nil
}

// Path returns the socket path, for the trace-session config.
func (s *Sink) Path() string { return s.path }

// Points returns how many trace points were decoded.
func (s *Sink) Points() int64 { return s.points.Load() }

// Dropped returns how many points the Sentry reported dropping. Non-zero means
// the sink could not keep up and the observation is incomplete — which must be
// surfaced, not averaged away.
func (s *Sink) Dropped() int64 { return s.dropped.Load() }

// Close stops the sink and removes the socket.
func (s *Sink) Close() error {
	if s.closed.Swap(true) {
		return nil
	}
	err := s.ln.Close()
	s.wg.Wait()
	_ = os.Remove(s.path)
	return err
}

func (s *Sink) acceptLoop() {
	defer s.wg.Done()
	for {
		c, err := s.ln.AcceptUnix()
		if err != nil {
			return // listener closed
		}
		s.wg.Add(1)
		go func() {
			defer s.wg.Done()
			s.serve(c)
		}()
	}
}

func (s *Sink) serve(c *net.UnixConn) {
	defer c.Close()
	buf := make([]byte, maxMessage)

	if err := handshake(c, buf); err != nil {
		s.reportError(fmt.Errorf("seccheck handshake: %w", err))
		return
	}
	for {
		n, err := c.Read(buf)
		if err != nil {
			return // sandbox exited
		}
		if err := s.handleMessage(buf[:n]); err != nil {
			s.reportError(err)
		}
	}
}

// handshake completes the version exchange. The Sentry writes its Handshake
// first and reads ours; this is the only write the monitor ever performs.
func handshake(c *net.UnixConn, buf []byte) error {
	n, err := c.Read(buf)
	if err != nil {
		return fmt.Errorf("read: %w", err)
	}
	var in pb.Handshake
	if err := proto.Unmarshal(buf[:n], &in); err != nil {
		return fmt.Errorf("unmarshal: %w", err)
	}
	if in.GetVersion() > protocolVersion {
		return fmt.Errorf("sandbox speaks protocol version %d, this build understands %d",
			in.GetVersion(), protocolVersion)
	}
	out, err := proto.Marshal(&pb.Handshake{Version: protocolVersion})
	if err != nil {
		return fmt.Errorf("marshal reply: %w", err)
	}
	if _, err := c.Write(out); err != nil {
		return fmt.Errorf("write reply: %w", err)
	}
	return nil
}

// handleMessage decodes one framed point.
func (s *Sink) handleMessage(msg []byte) error {
	if len(msg) < headerStructSize {
		return fmt.Errorf("seccheck: message too short (%d bytes)", len(msg))
	}
	hdrSize := binary.NativeEndian.Uint16(msg[0:2])
	msgType := binary.NativeEndian.Uint16(msg[2:4])
	dropped := binary.NativeEndian.Uint32(msg[4:8])

	// The header may grow in future versions, so its size is read rather than
	// assumed — but it must still lie inside the message.
	if int(hdrSize) < headerStructSize || int(hdrSize) > len(msg) {
		return fmt.Errorf("seccheck: header size %d outside message of %d bytes", hdrSize, len(msg))
	}
	if dropped > 0 {
		s.dropped.Store(int64(dropped))
	}

	io, ok, err := decodePoint(msgType, msg[hdrSize:])
	if err != nil {
		return err
	}
	if !ok {
		return nil // a point we do not model; forward compatibility
	}
	s.points.Add(1)
	if s.onIO != nil {
		s.onIO(io)
	}
	return nil
}

func (s *Sink) reportError(err error) {
	if s.onError != nil {
		s.onError(err)
	}
}

// decodePoint turns one protobuf payload into a FileIO. ok is false for point
// types this build does not model, which per the protocol's compatibility
// rules must be ignored rather than treated as an error.
func decodePoint(msgType uint16, payload []byte) (FileIO, bool, error) {
	switch pb.MessageType(msgType) {
	case pb.MessageType_MESSAGE_SYSCALL_OPEN:
		var m pb.Open
		if err := proto.Unmarshal(payload, &m); err != nil {
			return FileIO{}, false, fmt.Errorf("seccheck: decode open: %w", err)
		}
		return FileIO{
			Op:     OpOpen,
			Path:   resolveOpenPath(&m),
			FD:     m.GetFd(),
			Result: m.GetExit().GetResult(),
			Errno:  m.GetExit().GetErrorno(),
		}.withContext(m.GetContextData()), true, nil

	case pb.MessageType_MESSAGE_SYSCALL_READ:
		var m pb.Read
		if err := proto.Unmarshal(payload, &m); err != nil {
			return FileIO{}, false, fmt.Errorf("seccheck: decode read: %w", err)
		}
		return FileIO{
			Op:         OpRead,
			Path:       boundPath(m.GetFdPath()),
			FD:         m.GetFd(),
			Count:      m.GetCount(),
			Result:     m.GetExit().GetResult(),
			Offset:     m.GetOffset(),
			HasOffset:  m.GetHasOffset(),
			Errno:      m.GetExit().GetErrorno(),
			Positional: isPositional(m.GetSysno(), true),
		}.withContext(m.GetContextData()), true, nil

	case pb.MessageType_MESSAGE_SYSCALL_WRITE:
		var m pb.Write
		if err := proto.Unmarshal(payload, &m); err != nil {
			return FileIO{}, false, fmt.Errorf("seccheck: decode write: %w", err)
		}
		return FileIO{
			Op:         OpWrite,
			Path:       boundPath(m.GetFdPath()),
			FD:         m.GetFd(),
			Count:      m.GetCount(),
			Result:     m.GetExit().GetResult(),
			Offset:     m.GetOffset(),
			HasOffset:  m.GetHasOffset(),
			Errno:      m.GetExit().GetErrorno(),
			Positional: isPositional(m.GetSysno(), false),
		}.withContext(m.GetContextData()), true, nil

	case pb.MessageType_MESSAGE_SYSCALL_CLOSE:
		var m pb.Close
		if err := proto.Unmarshal(payload, &m); err != nil {
			return FileIO{}, false, fmt.Errorf("seccheck: decode close: %w", err)
		}
		return FileIO{
			Op:     OpClose,
			Path:   boundPath(m.GetFdPath()),
			FD:     m.GetFd(),
			Result: m.GetExit().GetResult(),
			Errno:  m.GetExit().GetErrorno(),
		}.withContext(m.GetContextData()), true, nil

	case pb.MessageType_MESSAGE_SYSCALL_CONNECT:
		var m pb.Connect
		if err := proto.Unmarshal(payload, &m); err != nil {
			return FileIO{}, false, fmt.Errorf("seccheck: decode connect: %w", err)
		}
		return FileIO{
			Op:     OpConnect,
			Path:   boundPath(m.GetFdPath()),
			FD:     m.GetFd(),
			Result: m.GetExit().GetResult(),
			Errno:  m.GetExit().GetErrorno(),
		}.withContext(m.GetContextData()), true, nil
	}
	return FileIO{}, false, nil
}

func (f FileIO) withContext(cd *pb.ContextData) FileIO {
	if cd == nil {
		return f
	}
	f.PID = cd.GetThreadGroupId()
	f.TID = cd.GetThreadId()
	f.ProcessName = cd.GetProcessName()
	f.ContainerID = cd.GetContainerId()
	f.TimeNs = cd.GetTimeNs()
	return f
}

// resolveOpenPath assembles an absolute path for an open.
//
// Open.pathname is the raw syscall argument and is frequently relative
// ("global/pg_filenode.map"); Open.fd_path is the dirfd's resolved path, and
// cwd covers AT_FDCWD. Read/write/close need none of this because their
// fd_path is already absolute — which is why watch() keys its matching on
// those (M0.3 finding).
func resolveOpenPath(m *pb.Open) string {
	name := m.GetPathname()
	if name == "" {
		return boundPath(m.GetFdPath())
	}
	if path.IsAbs(name) {
		return boundPath(name)
	}
	if dir := m.GetFdPath(); dir != "" {
		return boundPath(path.Join(dir, name))
	}
	if cwd := m.GetContextData().GetCwd(); cwd != "" {
		return boundPath(path.Join(cwd, name))
	}
	// Unresolvable: return it as-is rather than inventing a root, so a
	// consumer can see it is relative instead of matching the wrong file.
	return boundPath(name)
}

// isPositional distinguishes pread64/pwrite64 from read/write by syscall
// number, since both share one message type.
func isPositional(sysno uint64, isRead bool) bool {
	if isRead {
		return sysno == sysPread64ARM64 || sysno == sysPread64AMD64
	}
	return sysno == sysPwrite64ARM64 || sysno == sysPwrite64AMD64
}

// boundPath caps a path from the untrusted Sentry.
func boundPath(p string) string {
	if len(p) > maxPathLen {
		return p[:maxPathLen]
	}
	return p
}
